[package]
name = "url_shortner"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.217", features = ["derive"] }
sqlx = { version = "0.8.3", features = ["postgres", "chrono"] }
tokio = { version = "1.43.0", features = ["full"] }
