version: '3.8'

services:
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: url_shortener
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://pgbouncer_user:pgbouncer_password@db:6432/urlshortener
      - DRAGONFLY_DB_URL=redis://localhost:6379
    depends_on:
      - db
      - pgbouncer
    networks:
      - urlshortener-net

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: pgbouncer_user
      POSTGRES_PASSWORD: pgbouncer_password
      POSTGRES_DB: urlshortener
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - urlshortener-net

  pgbouncer:
    image: edoburu/pgbouncer:latest
    container_name: pgbouncer
    environment:
      - DATABASE_URL=postgres://pgbouncer_user:pgbouncer_password@db:5432/urlshortener
      - LISTEN_PORT=6432
    ports:
      - "6432:6432"
    depends_on:
      - db
    networks:
      - urlshortener-net

  load-balancer:
    image: traefik:v2.10
    container_name: load_balancer
    command:
      - "--api.insecure=true"
      - "--entrypoints.web.address=:8000"
    ports:
      - "8000:8000"
    networks:
      - urlshortener-net
    depends_on:
      - url-shortener

volumes:
  pgdata:

networks:
  urlshortener-net:
    driver: bridge